utils/module: fix importlib import
This worked most of the time by side effect: com.py imports importlib
and some following internal call probably trigger an import of the util
submodule.

Unfortunately, with ngl-python we are by-passing the com submodule since
a21e04b6e061ce14f5381beb981e941a9176ad72, which is causing the following
traceback when calling it with a script instead of a module:

    Traceback (most recent call last):
      File "/mnt/work/src/node.gl/pynodegl-utils/pynodegl_utils/module.py", line 30, in load_script
        spec = importlib.util.spec_from_file_location(name, path)
    AttributeError: module 'importlib' has no attribute 'util'