glcontext_egl: guard ngli_eglGetNativeClientBufferANDROID() declaration
struct AHardwareBuffer might not be declared in EGL/eglext.h, causing a
duplicated mismatching inside-parameter declaration of struct.

Fixes build issue on Ubuntu 18.10:
glcontext_egl.c:86:17: error: conflicting types for ‘ngli_eglGetNativeClientBufferANDROID’