pynodegl: require cython>=0.29.6
This version is required for our stack as it includes a fix for
https://github.com/cython/cython/issues/2819:

    Auto-encoding of Unicode strings to UTF-8 C/C++ strings failed in
    Python 3, even though the default encoding there is UTF-8.

Previous versions were causing the following issue:

    % python -c 'import pynodegl as ngl;print(ngl.Media("xxx"))'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "nodes_def.pyx", line 1357, in pynodegl.Media.__init__
        def __init__(self, const char *filename, sxplayer_min_level=None, time_anim=None, audio_tex=None, max_nb_packets=None, max_nb_frames=None, max_nb_sink=None, max_pixels=None, stream_idx=None, *args, **kwargs):
    TypeError: expected bytes, str found

All tests are passing starting this version.