ci/ios: add missing cpp entry
Fixes the following error with recent meson (1.2.0):

  ERROR: 'cpp' compiler binary not defined in cross or native file