specs: switch from YAML to JSON
Fix failing CI on MacOS:

      File "/Users/runner/work/gopro-lib-node.gl/gopro-lib-node.gl/venv/lib/python3.11/site-packages/setuptools/wheel.py", line 162, in _convert_metadata
        os.rename(dist_info, egg_info)
    OSError: [Errno 66] Directory not empty: '/Users/runner/work/gopro-lib-node.gl/gopro-lib-node.gl/pynodegl/.eggs/PyYAML-6.0-py3.11-macosx-10.9-universal2.egg/PyYAML-6.0.dist-info' -> '/Users/runner/work/gopro-lib-node.gl/gopro-lib-node.gl/pynodegl/.eggs/PyYAML-6.0-py3.11-macosx-10.9-universal2.egg/EGG-INFO'

Python 3.11 works locally on Linux, so it's likely something broken in
PyYAML wheel.

Similarly, trying ruamel.yaml fails on Windows:

    ImportError: cannot import name 'YAML' from 'ruamel.yaml' (d:\a\gopro-lib-node.gl\gopro-lib-node.gl\pynodegl\.eggs\ruamel.yaml.clib-0.2.7-py3.8-win-amd64.egg\ruamel\yaml\__init__.py)

It is thus decided to simplify the build by using a JSON specs instead
of YAML.