pgcraft: fix integer based types transmission between stages
Integers can not be interpolated like rational types are, so GLSL
require a qualifier such as "flat" to be used.

With MESA, it fixes the following error:
  error: if a fragment input is (or contains) an integer, then it must
  be qualified with 'flat'